#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean(å›ºä»¶)

on:
# å®šæ—¶è§¦å‘
  schedule:
    - cron: 0 01 * * *

# releaseè§¦å‘
#  release:
#    types: [published]

# ç‚¹èµè§¦å‘
  watch:
    types: [started]

# ç¼–è¾‘è§¦å‘
#  push:
#    branches: 
#       - master

# configè§¦å‘
#  paths:
#    - 'x86_64.config'

#FREE_UP_DISK é‡Šæ”¾ç£ç›˜ç©ºé—´
#SSH_ACTIONS å¼€å¯SSHè¿æ¥
#UPLOAD_BIN_DIRä¸Šä¼ BINç›®å½•
#UPLOAD_FIRMWAREä¸Šä¼ å›ºä»¶ç›®å½•

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  DIY_SH: OpenWrt-R7800-Lean.sh
  FREE_UP_DISK: true
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  TARGET: ipq806x
  SUBTARGET: generic
  DEVICE: openwrt-ipq806x-netgear_r7800
  UPLOAD_TMP_LINK: true
  DOWNLOAD_URL_FILE: Tmp-Link-Url.txt
  BUILD_USER: ClayMoreBoy
  CREATE_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: æ ¡éªŒæœ¬åœ°æ–‡ä»¶
      uses: actions/checkout@master

    - name: åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/*
        sudo -E apt-get -qq update
        sudo apt-get -y install asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache flex g++ gawk gcc gcc-multilib gettext git git-core help2man htop lib32gcc1 libc6-dev-i386 libglib2.0-dev libncurses5-dev libssl-dev libtool libz-dev libelf-dev make msmtp ncurses-term ocaml-nox p7zip p7zip-full patch qemu-utils sharutils subversion texinfo uglifyjs unzip upx xmlto yui-compressor zlib1g-dev make cmake device-tree-compiler  g++-multilib  python3.5
        curl -fsSL https://github.com/ClayMoreBoy/dotfiles/raw/master/.bashrc >> ~/.bashrc

    - name: é‡Šæ”¾ç£ç›˜ç©ºé—´
      if: env.FREE_UP_DISK == 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi `docker images -q`
        sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: å…‹éš†æºä»£ç  by bobotoy
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(date "+%Y-%m-%d")"

    - name: æ›´æ–°æº
      working-directory: ./openwrt
      run:  |
        echo "src-git lienol https://github.com/Lienol/openwrt-package" >> feeds.conf.default && cat feeds.conf.default
        ./scripts/feeds clean
        ./scripts/feeds update -a
        rm -rf feeds/lienol/lienol/v2ray
        rm -rf feeds/lienol/lienol/openssl1.1
        rm -rf feeds/lienol/lienol/trojan
        rm -rf feeds/lienol/lienol/ipt2socks
        rm -rf feeds/lienol/lienol/shadowsocks-libev-new
        rm -rf feeds/lienol/lienol/shadowsocksr-libev
        rm -rf feeds/lienol/lienol/pdnsd-alt
        rm -rf feeds/lienol/package/verysync
        rm -rf feeds/lienol/lienol/luci-app-verysync
        rm -rf package/lean/kcptun
        rm -rf package/lean/luci-app-kodexplorer
        rm -rf package/lean/luci-app-pppoe-relay
        rm -rf package/lean/luci-app-pptp-server
        rm -rf package/lean/luci-app-v2ray-server

    - name: å®‰è£…æº
      working-directory: ./openwrt
      run:  ./scripts/feeds install -a

    - name: åˆ›å»ºè‡ªå®šä¹‰é…ç½®æ–‡ä»¶ - OpenWrt-R7800
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: å¼€å¯SSHè¿œç¨‹è¿æ¥
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    - name: ä¸‹è½½è½¯ä»¶åŒ…
      working-directory: ./openwrt
      id: package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ç¼–è¯‘å›ºä»¶
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"
        
    - name: ä¸Šä¼ é…ç½®æ–‡ä»¶
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: .config
        path: openwrt/.config
    
    - name: ä¸Šä¼ åŒ…
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: packages
        path: openwrt/bin/packages
        
    - name: ä¸Šä¼ å®˜æ–¹é•œåƒ
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-squashfs-factory.img
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-factory.img
    
    - name: ä¸Šä¼ ç³»ç»Ÿå‡çº§é•œåƒ
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: ${{ env.DEVICE }}-squashfs-sysupgrade.bin
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-sysupgrade.bin
    
    - name: ä¸Šä¼ é•œåƒæ–‡ä»¶å“ˆå¸Œå€¼
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success'
      with:
        name: sha256sums
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums
    
    - name: ä¸Šä¼ æ–‡ä»¶åˆ°Tmp.Link by SuLingGG
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      run: |
        cd openwrt/bin/packages
        zip -q -r ../targets/$TARGET/$SUBTARGET/packages.zip *
        cd ../targets/$TARGET/$SUBTARGET
        rm -f *.manifest
        rm -f *uImage
        find . -maxdepth 1 ! -name "$DOWNLOAD_URL_FILE" -type f -exec echo {} >> $DOWNLOAD_URL_FILE \; -exec curl -k -F "file=@{}" -F "token=${{ secrets.TMP_LINK_TOKEN }}" -F "model=3" -X POST "https://connect.tmp.link/api_v2/cli_uploader" -s >> $DOWNLOAD_URL_FILE \;
        sed -i 's/\.\///g' $DOWNLOAD_URL_FILE
        sed -i '/^Upload.*/d' $DOWNLOAD_URL_FILE
        sed -i '/^Thank.*/d' $DOWNLOAD_URL_FILE
        sed -i '/Download/G' $DOWNLOAD_URL_FILE
    
    - name: ä¸Šä¼ ä¸‹è½½åœ°å€æ–‡ä»¶
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      with:
        name: ${{ env.DOWNLOAD_URL_FILE }}
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DOWNLOAD_URL_FILE }}
    
    - name: åˆ›å»ºå‘å¸ƒ by ylqjgm
      id: create_release
      uses: actions/create-release@master
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_DATE }}
        release_name: Netgear R7800 ğŸš€ | è‡ªåŠ¨ç¼–è¯‘ / ${{ env.RELEASE_DATE }}
        body: |
            ${{ github.event.commits[0].message }}
            å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ï¼ˆç¼–è¯‘å‰çš„æœ€åä¸€æ¬¡å¤§é›•æºç æ›´æ–°è®°å½•ï¼‰
            ${{ env.useVersionInfo }}
        draft: false
        prerelease: false

    - name: ä¸Šä¼ å‘å¸ƒ
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-factory.img
          asset_name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-factory.img
          asset_content_type: application/octet-stream

    - name: ä¸Šä¼ å‘å¸ƒ
      uses: actions/upload-release-asset@v1
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DEVICE }}-squashfs-sysupgrade.bin
          asset_name: ${{ env.BUILD_USER }}-${{ env.DATE }}-${{ env.DEVICE }}-squashfs-sysupgrade.bin
          asset_content_type: application/octet-stream

    - name: ä¸Šä¼ å‘å¸ƒ
      uses: actions/upload-release-asset@v1
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./openwrt/.config
          asset_name: .config
          asset_content_type: application/octet-stream

    - name: ä¸Šä¼ å‘å¸ƒ
      uses: actions/upload-release-asset@v1
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/packages
          asset_name: Packages.tar.gz
          asset_content_type: application/octet-stream

    - name: ä¸Šä¼ å‘å¸ƒ
      uses: actions/upload-release-asset@v1
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/sha256sums
          asset_name: sha256sums
          asset_content_type: application/octet-stream

    - name: å¾®ä¿¡é€šçŸ¥
      run: curl https://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=R7800_Lean_${{ env.DATE }}ç¼–è¯‘å®Œæˆ
