#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean

on:
# å®šæ—¶è§¦å‘
  schedule:
    - cron: 0 1 * * *

# Release å‘å¸ƒè§¦å‘
#  release:
#    types: [published]

# ç‚¹èµè§¦å‘
  watch:
    types: [started]

# ç¼–è¾‘è§¦å‘
#  push:
#    branches: 
#       - master

env:
  # æº
  REPO_URL: https://github.com/project-openwrt/openwrt
  # åˆ†æ”¯
  REPO_BRANCH: openwrt-18.06-dev
  # è„šæœ¬
  DIY_SH: OpenWrt-R7800-Lean.sh
  # å¼€å¯SSHè¿æ¥
  SSH_ACTIONS: false
  # ä¸Šä¼ åˆ†æ”¯
  UPLOAD_BRANCH: true
  # åˆ†æ”¯
  BRANCH: R7800
  # Github ç”¨æˆ·å
  GITHUB_USER_NAME: ClayMoreBoy
  # Github é‚®ç®±
  GITHUB_USER_EMAIL: ${{ secrets.EMAIL }}
  # Github
  GITHUB: github.com/ClayMoreBoy/OpenWrt-Actions-R7800.git
  # ä¸Šä¼ å›ºä»¶
  UPLOAD_FIRMWARE: true
  # ä¸Šä¼ åˆ°å¥¶ç‰›å¿«ä¼ 
  UPLOAD_COWTRANSFER: true
  # ä¸Šä¼ åˆ°TMP.link
  UPLOAD_TMP_LINK: true
  DOWNLOAD_URL_FILE: Tmp-Link-Url.txt
  TARGET: ipq806x
  SUBTARGET: generic
  # åˆ›å»º+ä¸Šä¼ å‘å¸ƒ
  CREATE_RELEASE: true
  # ç¼–è¯‘è€…
  BUILD_USER: ClayMoreBoy
  # å¾®ä¿¡é€šçŸ¥
  SEND_WECHAT_MSG: true

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    # æ ¡éªŒæœ¬åœ°æ–‡ä»¶
    - name: Checkout
      uses: actions/checkout@master

    # åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E swapoff /swapfile
        sudo -E rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* mssql-tools msodbcsql17
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        sudo -E ln -sf /usr/bin/gcc-8 /usr/bin/gcc
        sudo -E ln -sf /usr/bin/g++-8 /usr/bin/g++
        sudo -E ln -sf /usr/bin/gcc-ar-8 /usr/bin/gcc-ar
        sudo -E ln -sf /usr/bin/gcc-nm-8 /usr/bin/gcc-nm
        sudo -E ln -sf /usr/bin/gcc-ranlib-8 /usr/bin/gcc-ranlib
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php

    # å…‹éš†æºä»£ç  By bobotoy
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(TZ=UTC-8 date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(TZ=UTC-8 date "+%Y-%m-%d")"

    # æ›´æ–°æº
    - name: Update Feeds
      if: env.REPO_URL != 'https://github.com/coolsnowwolf/lede'
      working-directory: ./openwrt
      run:  |
        ./scripts/feeds clean
        ./scripts/feeds update -a

    # å®‰è£…æº
    - name: Install Feeds
      if: env.REPO_URL != 'https://github.com/coolsnowwolf/lede'
      working-directory: ./openwrt
      run:  ./scripts/feeds install -a

    # åŠ è½½è‡ªå®šä¹‰é…ç½®æ–‡ä»¶
    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    # SSHè¿æ¥
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    # ä¸‹è½½è½¯ä»¶åŒ…
    - name: Make Download
      working-directory: ./openwrt
      id: package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    # ç¼–è¯‘å›ºä»¶
    - name: Compile Firmware
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"        
    
    # ä¸Šä¼ åˆ°åˆ†æ”¯ By yfdoor
    - name: Upload Branch
      if: env.UPLOAD_BRANCH == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
          cd openwrt/bin
          git init
          git config user.name $GITHUB_USER_NAME
          git config user.email $GITHUB_USER_EMAIL
          git add .
          git commit -m "Update OpenWrt_"$BRANCH
          git push --force --quiet https://${{ secrets.RELEASE_TOKEN }}@$GITHUB HEAD:OpenWrt-$BRANCH
    
    # æ•´ç†æ–‡ä»¶
    - name: Organize Files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        rm -rf *uImage
        rm -rf *.manifest
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
    
    # ä¸Šä¼ å›ºä»¶
    - name: Upload Firmware Directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt-Firmware-${{ env.BRANCH }}-${{ env.BUILD_USER }}-${{ env.DATE }}
        path: ${{ env.FIRMWARE }}

    # ä¸Šä¼ å›ºä»¶åˆ°å¥¶ç‰›å¿«ä¼ 
    - name: Upload Firmware To CowTransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && steps.compile.outputs.status == 'success'
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer-uploader -b 2621440 -s -p 99 -t 3 --hash ${FIRMWARE} > cowtransfer.txt
        cat cowtransfer.txt
        echo "::set-env name=COWTRANSFER_URL::$(cat cowtransfer.txt | grep https | cut -f2 -d" ")"
    
    # ä¸Šä¼ æ–‡ä»¶åˆ°Tmp.Link By SuLingGG
    - name: Upload Firmwares To Tmp.Link
      if: env.UPLOAD_TMP_LINK == 'true' && steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/*/*
        find . -maxdepth 1 ! -name "$DOWNLOAD_URL_FILE" -type f -exec echo {} >> $DOWNLOAD_URL_FILE \; -exec curl -k -F "file=@{}" -F "token=${{ secrets.TMP_LINK_TOKEN }}" -F "model=3" -X POST "https://connect.tmp.link/api_v2/cli_uploader" -s >> $DOWNLOAD_URL_FILE \;
        sed -i 's/\.\///g' $DOWNLOAD_URL_FILE
        sed -i '/^Upload.*/d' $DOWNLOAD_URL_FILE
        sed -i '/^Thank.*/d' $DOWNLOAD_URL_FILE
        sed -i '/Download/G' $DOWNLOAD_URL_FILE
    
    # ä¸Šä¼ ä¸‹è½½åœ°å€æ–‡ä»¶
    - name: Upload Download Url File
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      with:
        name: ${{ env.DOWNLOAD_URL_FILE }}
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DOWNLOAD_URL_FILE }}
    
    # ç”Ÿæˆæ ‡ç­¾
    - name: Generate Tag
      id: tag
      if: env.CREATE_RELEASE == 'true' && steps.compile.outputs.status == 'success'
      run: |
        echo "ğŸ”— [Cowtransfer | å¥¶ç‰›å¿«ä¼ ](${{ env.COWTRANSFER_URL }})" >> release.txt
        echo "::set-output name=status::success"
    
    # å‘è¡Œå›ºä»¶
    - name: Upload Firmware To Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: Netgear ${{ env.BRANCH }} ğŸš€ | è‡ªåŠ¨ç¼–è¯‘ / ${{ env.RELEASE_DATE }}
        tag_name: ${{ env.RELEASE_DATE }}
        body: |            
            1ã€æœ¬å›ºä»¶ä¸ºè‡ªåŠ¨ç¼–è¯‘
            2ã€å‘è¡Œç‰ˆä¸­åªæä¾›å®Œæ•´çš„å›ºä»¶
            3ã€éœ€è¦å•ç‹¬IPKè¯·åˆ°åˆ†æ”¯ä¸‹è½½
            4ã€æºç ï¼š${{ env.REPO_URL }}
            -- Build by ${{ env.BUILD_USER }} @ with Github Action on ${{ env.RELEASE_DATE }}
            ğŸš€ Auto build | è‡ªåŠ¨ç¼–è¯‘
            ğŸ”— [Cowtransfer | å¥¶ç‰›å¿«ä¼ ](${{ env.COWTRANSFER_URL }})        
            å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ï¼ˆç¼–è¯‘å‰çš„æœ€åä¸€æ¬¡å¤§é›•æºç æ›´æ–°è®°å½•ï¼‰            
            ${{ env.useVersionInfo }}
            ${{ github.event.commits[0].message }}
        files: ${{ env.FIRMWARE }}/*

    # å¾®ä¿¡é€šçŸ¥
    - name: WeChat Notification
      if: env.SEND_WECHAT_MSG == 'true' && steps.compile.outputs.status == 'success'
      uses: emon100/Action-Serverchan@master
      with:
        SCKEY: ${{ secrets.SCKEY }}
        text: ${{ env.BRANCH }}å›ºä»¶ç¼–è¯‘å®Œæˆï¼
        desp: æºç :${{ env.REPO_URL }} åˆ†æ”¯ï¼š${{ env.REPO_BRANCH }}
