#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean

on:
# å®šæ—¶è§¦å‘
  schedule:
    - cron: 0 01 * * *

# Release å‘å¸ƒè§¦å‘
#  release:
#    types: [published]

# ç‚¹èµè§¦å‘
  watch:
    types: [started]

# ç¼–è¾‘è§¦å‘
#  push:
#    branches: 
#       - master

# Config é…ç½®è§¦å‘(æœ¬é¡¹ç›®æ— è¯¥é…ç½®)
#  paths:
#    - 'x86_64.config'

env:
  # æº
  REPO_URL: https://github.com/coolsnowwolf/lede
  # åˆ†æ”¯
  REPO_BRANCH: master
  # è„šæœ¬
  DIY_SH: OpenWrt-R7800-Lean.sh
  # é‡Šæ”¾ç£ç›˜ç©ºé—´
  FREE_UP_DISK: true
  # Lienolæ’ä»¶æº
  LIENOL_PACKAGES: true
  # å¼€å¯SSHè¿æ¥
  SSH_ACTIONS: false
  # Github ç”¨æˆ·å
  GITHUB_USER_NAME: ClayMoreBoy
  # Github é‚®ç®±
  GITHUB_USER_EMAIL: claymor3.sky@gmail.com
  # ä¸Šä¼ åˆ†æ”¯
  UPLOAD_BRANCH: true
  # åˆ†æ”¯
  BRANCH: R7800
  # ä¸Šä¼ æ’ä»¶åŒ…
  UPLOAD_PACKAGES: true
  # ä¸Šä¼ å›ºä»¶
  UPLOAD_FIRMWARE: true
  TARGET: ipq806x
  SUBTARGET: generic
  DEVICE: openwrt-ipq806x-netgear_r7800
  # ä¸Šä¼ åˆ°å¥¶ç‰›å¿«ä¼ 
  UPLOAD_COWTRANSFER: true
  # ä¸Šä¼ åˆ°TMP.link
  UPLOAD_TMP_LINK: true
  DOWNLOAD_URL_FILE: Tmp-Link-Url.txt
  # ç¼–è¯‘è€…
  BUILD_USER: ClayMoreBoy
  # åˆ›å»º+ä¸Šä¼ å‘å¸ƒ
  CREATE_RELEASE: true
  # å¾®ä¿¡é€šçŸ¥
  SEND_WECHAT_MSG: true
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    # æ ¡éªŒæœ¬åœ°æ–‡ä»¶
    - name: Checkout
      uses: actions/checkout@master

    # åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d
        sudo -E apt-get -qq update
        sudo apt-get -y install asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache flex g++ gawk gcc gcc-multilib gettext git git-core help2man htop lib32gcc1 libc6-dev-i386 libglib2.0-dev libncurses5-dev libssl-dev libtool libz-dev libelf-dev make msmtp ncurses-term ocaml-nox p7zip p7zip-full patch qemu-utils sharutils subversion texinfo uglifyjs unzip upx xmlto yui-compressor zlib1g-dev make cmake device-tree-compiler  g++-multilib  python3.5
        curl -fsSL https://github.com/ClayMoreBoy/dotfiles/raw/master/.bashrc >> ~/.bashrc

    # é‡Šæ”¾ç£ç›˜ç©ºé—´
    - name: Free Up Disk Space
      if: env.FREE_UP_DISK == 'true'
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
        docker rmi `docker images -q`
        sudo -E apt-get -q purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    # å…‹éš†æºä»£ç  By bobotoy
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(date "+%Y-%m-%d")"

    # å¢åŠ  PassWall æ’ä»¶æº By rohu168
    - name: Update and install feeds passwall
      if: env.LIENOL_PACKAGES == 'true'
      run: |
        chmod +x passwall.sh && cp passwall.sh ./openwrt && cd openwrt && ./passwall.sh
    
    # æ›´æ–°æº
    - name: Update Feeds
      if: env.LIENOL_PACKAGES == 'false'
      working-directory: ./openwrt
      run:  |
        ./scripts/feeds clean
        ./scripts/feeds update -a

    # å®‰è£…æº
    - name: Install Feeds
      if: env.LIENOL_PACKAGES == 'false'
      working-directory: ./openwrt
      run:  ./scripts/feeds install -a

    # åŠ è½½è‡ªå®šä¹‰é…ç½®æ–‡ä»¶
    - name: Load Custom Configuration
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    # SSHè¿æ¥
    - name: SSH connection to Actions
      uses: P3TERX/debugger-action@master
      if: env.SSH_ACTIONS == 'true'

    # ä¸‹è½½è½¯ä»¶åŒ…
    - name: Make Download
      working-directory: ./openwrt
      id: package
      run: |
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    
    # ç¼–è¯‘å›ºä»¶
    - name: Compile Firmware
      working-directory: ./openwrt
      id: compile
      run: |
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"        
    
    # ä¸Šä¼ åˆ°åˆ†æ”¯ By yfdoor
    - name: Upload Branch
      if: env.UPLOAD_BRANCH == 'true' && steps.compile.outputs.status == 'success'
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
          cd openwrt/bin
          git init
          git config user.name $GITHUB_USER_NAME
          git config user.email $GITHUB_USER_EMAIL
          git add .
          git commit -m "Update OpenWrt_"$BRANCH
          git push --force --quiet https://$GITHUB_TOKEN@github.com/ClayMoreBoy/OpenWrt-Actions-R7800.git HEAD:OpenWrt_$BRANCH
    
    # æ•´ç†æ–‡ä»¶
    - name: Organize Files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        echo "::set-env name=FIRMWARE::$PWD"
        echo "::set-output name=status::success"
    
    # ä¸Šä¼ å›ºä»¶
    - name: Upload Firmware Directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_firmware
        path: ${{ env.FIRMWARE }}

    # ä¸Šä¼ å›ºä»¶åˆ°å¥¶ç‰›å¿«ä¼ 
    - name: Upload Firmware To CowTransfer
      if: env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        curl -sL https://git.io/cowtransfer | sh
        ./cowtransfer-uploader -b 2621440 -s -p 99 -t 3 --hash ${FIRMWARE} > cowtransfer.txt
        cat cowtransfer.txt
        echo "::set-env name=COWTRANSFER_URL::$(cat cowtransfer.txt | grep https | cut -f2 -d" ")"
    
    # ä¸Šä¼ æ–‡ä»¶åˆ°Tmp.Link By SuLingGG
    - name: Upload Firmwares To Tmp.Link
      if: env.UPLOAD_TMP_LINK == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        rm -f *.manifest
        rm -f *uImage
        find . -maxdepth 1 ! -name "$DOWNLOAD_URL_FILE" -type f -exec echo {} >> $DOWNLOAD_URL_FILE \; -exec curl -k -F "file=@{}" -F "token=${{ secrets.TMP_LINK_TOKEN }}" -F "model=3" -X POST "https://connect.tmp.link/api_v2/cli_uploader" -s >> $DOWNLOAD_URL_FILE \;
        sed -i 's/\.\///g' $DOWNLOAD_URL_FILE
        sed -i '/^Upload.*/d' $DOWNLOAD_URL_FILE
        sed -i '/^Thank.*/d' $DOWNLOAD_URL_FILE
        sed -i '/Download/G' $DOWNLOAD_URL_FILE
    
    # ä¸Šä¼ ä¸‹è½½åœ°å€æ–‡ä»¶
    - name: Upload Download Url File
      uses: actions/upload-artifact@master
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_TMP_LINK == 'true'
      with:
        name: ${{ env.DOWNLOAD_URL_FILE }}
        path: openwrt/bin/targets/${{ env.TARGET }}/${{ env.SUBTARGET }}/${{ env.DOWNLOAD_URL_FILE }}
    
    # å‘è¡Œå›ºä»¶
    - name: Upload Firmware To Release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        name: Netgear R7800 ğŸš€ | è‡ªåŠ¨ç¼–è¯‘ / ${{ env.RELEASE_DATE }}
        tag_name: ${{ env.RELEASE_DATE }}
        body: |            
            1ã€æœ¬å›ºä»¶ä¸ºè‡ªåŠ¨ç¼–è¯‘
            2ã€å‘è¡Œç‰ˆä¸­åªæä¾›å®Œæ•´çš„å›ºä»¶
            3ã€éœ€è¦å•ç‹¬IPKè¯·åˆ°åˆ†æ”¯ä¸‹è½½
            4ã€æºç ï¼š${{ env.REPO_URL }}
            5ã€åˆ†æ”¯ï¼š${{ env.REPO_BRANCH }}
            -- Build by ${{ env.BUILD_USER }} @ with Github Action on ${{ env.RELEASE_DATE }}
            ğŸš€ Auto build | è‡ªåŠ¨ç¼–è¯‘
            ğŸ”— [Cowtransfer | å¥¶ç‰›å¿«ä¼ ](${{ env.COWTRANSFER_URL }})
            å½“å‰ä½¿ç”¨ç‰ˆæœ¬:ï¼ˆç¼–è¯‘å‰çš„æœ€åä¸€æ¬¡å¤§é›•æºç æ›´æ–°è®°å½•ï¼‰
            ${{ github.event.commits[0].message }}
            ${{ env.useVersionInfo }}
        files: ${{ env.FIRMWARE }}/*

    # å¾®ä¿¡é€šçŸ¥ By rohu168
    - name: Sending WeChat Notification
      if: env.SEND_WECHAT_MSG == 'true' && !cancelled()
      uses: yakumioto/serverchan-action@v1
      with:
        key: ${{ secrets.SCKEY }}
        text: ${{ env.BRANCH }}å›ºä»¶ç¼–è¯‘å®Œæˆï¼
        desp: æºç :${{ env.REPO_URL }}
