#=================================================
# https://github.com/ClayMoreBoy/OpenWrt-Actions-R7800
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: ClayMoreBoy
# Github: https://github.com/ClayMoreBoy
#=================================================

name: OpenWrt-R7800-Lean-Config(é…ç½®æå–)

on:
# å®šæ—¶è§¦å‘
  schedule:
    - cron: 0 01 * * 5

# releaseè§¦å‘
#  release:
#    types: [published]

# ç‚¹èµè§¦å‘
#  watch:
#    types: [started]

# ç¼–è¾‘è§¦å‘
#  push:
#    branches: 
#      - master

# configè§¦å‘
#  paths:
#    - '.config'

#SSH_ACTIONS å¼€å¯SSHè¿æ¥
#UPLOAD_BIN_DIRä¸Šä¼ BINç›®å½•
#UPLOAD_FIRMWAREä¸Šä¼ å›ºä»¶ç›®å½•

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  DIY_SH: OpenWrt-R7800-Lean-Config.sh
  SSH_ACTIONS: false
  UPLOAD_BIN_DIR: false
  UPLOAD_CONFIG: true
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    steps:
    - name: æ ¡éªŒæœ¬åœ°æ–‡ä»¶
      uses: actions/checkout@master
        
    - name: åˆå§‹åŒ–ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo -E swapoff /swapfile
        sudo -E rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* mssql-tools msodbcsql17
        sudo -E apt-get update -y
        sudo -E apt-get full-upgrade -y
        sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-8 gcc++-8 gcc-8-multilib g++-8-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler
        sudo -E apt-get autoremove -y --purge
        sudo -E apt-get clean -y
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
        
    # å…‹éš†æºä»£ç  By bobotoy
    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        useVersionInfo=$(git show -s --date=short --format="Author: %an<br/>Date: %cd<br/>Commit: %s")
        echo "::set-env name=useVersionInfo::$useVersionInfo"
        echo "::set-env name=DATE::$(date "+%Y%m%d")"
        echo "::set-env name=RELEASE_DATE::$(date "+%Y-%m-%d")"

    - name: æ›´æ–°æº
      working-directory: ./openwrt
      run: ./scripts/feeds update -a

    - name: å®‰è£…æº
      working-directory: ./openwrt
      run:  ./scripts/feeds install -a

    - name: åˆ›å»ºè‡ªå®šä¹‰é…ç½®æ–‡ä»¶ - OpenWrt-R7800
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        ../$DIY_SH
        make defconfig

    - name: æ•´ç†æ–‡ä»¶
      id: organize
      if: env.UPLOAD_CONFIG == 'true' && !cancelled()
      run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv openwrt/.config  ./artifact/.config
    
    - name: æå–æ—¥æœŸ
      run: |
        date=$(date +%Yå¹´%mæœˆ%dæ—¥)
        echo "::set-env name=DATE::$date"
        
    - name: ä¸Šä¼ é…ç½®
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt-Lean-Config-R7800-${{ env.DATE }}
        path: ./artifact/    

    # å¾®ä¿¡é€šçŸ¥
    - name: WeChat Notification      
      uses: emon100/Action-Serverchan@master
      with:
        SCKEY: ${{ secrets.SCKEY }}
        text: ${{ env.BRANCH }}å›ºä»¶ç¼–è¯‘å®Œæˆï¼
        desp: | 
             1ã€æºç :${{ env.REPO_URL }}
             2ã€åˆ†æ”¯ï¼š${{ env.REPO_BRANCH }}
             -- Build by ${{ env.BUILD_USER }} @ with Github Action on ${{ env.RELEASE_DATE }}
             ğŸš€ Auto build | è‡ªåŠ¨ç¼–è¯‘
             ${{ env.useVersionInfo }}
